### ISSUE TITLE
How to uninstall the mod

### ISSUE THREAD

**Issue by TecEash1** [paulevsGitch/EdenRing#58]
Hi, This mod is great, but I need to try uninstall it for a test for my mc server. If I just delete the JAR file will everything go..?? or will the blocks just become broken textures. How do I uninstall it correctly?

**Comment by paulevsGitch** [comment]
Uninstalling dimension mod will result with world corruption. You will need to manually edit level.dat and remove dimension entry manually together with removing mod jar. After launching you still can have issues, for example with structure registry.


> will the blocks just become broken textures

No, they will completely disappear, same as items


> How do I uninstall it correctly?

There only one correct uninstall for any worldgen or dimension mod: completely new world, all other ways can/will result with issues. It is not impossible to remove mod from existing world, but you should do it on your own risk and make backups

**Comment by TecEash1** [comment]
is there a way to disable the dimension then?

**Comment by paulevsGitch** [comment]
I already described that:

> You will need to manually edit level.dat and remove dimension entry manually together with removing mod jar

**Comment by paulevsGitch** [comment]
If you want to disable only entering the dimension, well, it is not possible

**Comment by TecEash1** [comment]
> I already described that:
> 
> 
> 
> > You will need to manually edit level.dat and remove dimension entry manually together with removing mod jar

If I delete all the BCLIB stuff and eden ring stuff in the level.dat file and also delete the eden ring folder from the dimensions folder, will it be fine then, assuming that the BCLIB things will regenerate

**Comment by paulevsGitch** [comment]
> If I delete all the BCLIB stuff and eden ring stuff in the level.dat file and also delete the eden ring folder from the dimensions folder, will it be fine then, assuming that the BCLIB things will regenerate

You will need not only delete things, but also recreate structure as it should be in vanilla world

> if you just deleted the level.dat file wouldn't it just regenerate when the server next starts

If you will delete it technically you will lost your world, as level.dat is your world. MC automatically creates backup of that file, but if even backup will be missing you will just lost your world. If server will try to generate same world with same name it will have different seed, or it can fail to generate due to already existing folders

> also with the eden ring dimension gone from the dimension list why would there be problems?

Any dimension is not just folder, it is a lot of additional data, from level.dat structure up to different registries. If MC will lost the source of that data all other things will be corrupted: the game was not supposed to be modded and it doesn't support removing already existing data. If you will just remove the mod you will have only Overworld, and you will lost all other dimensions. Their chunk data will be saved, so it is possible to connect them again, but you will need to do this by hand

**Comment by TecEash1** [comment]
o ok - that's much more complex than I thought 😞
